name: Pylint

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment
      run: python -m venv venv
      working-directory: ${{ github.workspace }}

    - name: Activate virtual environment and install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install anybadge
        deactivate
      working-directory: ${{ github.workspace }}

    - name: Analyze code with Pylint
      run: |
        source venv/bin/activate
        pylint $(git ls-files 'python/lammpsinputbuilder/*.py') --output-format=text --exit-zero | tee pylint_report.txt
        score=$(sed -n 's/Your code has been rated at \(.*\)/\1/p' pylint_report.txt)
        echo "PyLint score is: $score"
        anybadge --label "Pylint" --value $score --file=public/pylint_badge.svg
        deactivate
      working-directory: ${{ github.workspace }} 

    - name: Upload Pylint badge
      uses: actions/upload-artifact@v3
      with:
        name: pylint_badge
        path: public/pylint_badge.svg

        