name: Pylint

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment
      run: python -m venv venv
      working-directory: ${{ github.workspace }}

    - name: Activate virtual environment and install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install anybadge
        deactivate
      working-directory: ${{ github.workspace }}

    - name: Analyze code with Pylint
      # anybadge --label "Pylint" --value $score --file=public/pylint_badge.svg
      run: |
        source venv/bin/activate
        pylint $(git ls-files 'python/lammpsinputbuilder/*.py') --output-format=text --fail-under=7.0 | tee pylint_report.txt
        score=$(sed -n 's/Your code has been rated at \(.*\)/\1/p' pylint_report.txt)
        echo "PyLint score is: $score"
        deactivate
      working-directory: ${{ github.workspace }} 

    - name: Create badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: bc29e267d35fad12ca2de2bd7138ecfc
        filename: test.json
        label: "Pylint"
        message: ${{ env.score }}
        color: green


